In [48]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from sklearn.preprocessing import Imputer
import random

import seaborn as sns

from imports import categorical_encoder
from imports import dataframe_selector
from imports import categorical_imputer

# Importing the dataset]
dataset_b = pd.read_csv('data/train.csv')
train_dataset= dataset_b.copy()

In [49]:
train_dataset

,ACTION,RESOURCE,MGR_ID,ROLE_ROLLUP_1,ROLE_ROLLUP_2,ROLE_DEPTNAME,ROLE_TITLE,ROLE_FAMILY_DESC,ROLE_FAMILY,ROLE_CODE
0,1,39353,85475,117961,118300,123472,117905,117906,290919,117908
1,1,17183,1540,117961,118343,123125,118536,118536,308574,118539
2,1,36724,14457,118219,118220,117884,117879,267952,19721,117880
3,1,36135,5396,117961,118343,119993,118321,240983,290919,118322
4,1,42680,5905,117929,117930,119569,119323,123932,19793,119325
5,0,45333,14561,117951,117952,118008,118568,118568,19721,118570
6,1,25993,17227,117961,118343,123476,118980,301534,118295,118982
7,1,19666,4209,117961,117969,118910,126820,269034,118638,126822
8,1,31246,783,117961,118413,120584,128230,302830,4673,128231
9,1,78766,56683,118079,118080,117878,117879,304519,19721,117880
10,1,4675,3005,117961,118413,118481,118784,117906,290919,118786
11,1,15030,94005,117902,118041,119238,119093,138522,119095,119096
12,1,79954,46608,118315,118463,122636,120773,123148,118960,120774
13,1,4675,50997,91261,118026,118202,119962,168365,118205,119964
14,1,95836,18181,117961,118343,118514,118321,117906,290919,118322
15,1,19484,6657,118219,118220,118221,117885,117886,117887,117888
16,1,114267,23136,117961,118052,119742,118321,117906,290919,118322
17,1,35197,57715,117961,118446,118701,118702,118703,118704,118705
18,1,86316,7002,117961,118343,123125,118278,132715,290919,118279
19,1,27785,5636,117961,118413,122007,118321,117906,290919,118322
20,1,37427,5220,117961,118300,118458,120006,303717,118424,120008
21,1,15672,111936,117961,118300,118783,117905,240983,290919,117908
22,1,92885,744,117961,118300,119181,118777,279443,308574,118779
23,1,1020,85475,117961,118300,120410,118321,117906,290919,118322
24,1,4675,7551,117961,118052,118867,118259,117906,290919,118261
25,1,41334,28253,118315,118463,123089,118259,128796,290919,118261
26,1,77385,14829,117961,118052,119986,117905,117906,290919,117908
27,1,20273,11506,118216,118587,118846,179731,128361,117887,117973
28,1,78098,46556,118090,118091,117884,118568,165015,19721,118570
29,1,79328,4219,117961,118300,120312,120313,144958,118424,120315
...,...,...,...,...,...,...,...,...,...,...
32739,1,20293,27915,117926,117927,117920,118568,281735,19721,118570
32740,1,40867,3197,117961,118386,120361,117905,117906,290919,117908
32741,1,22402,6199,117961,118225,120663,118321,117906,290919,118322
32742,1,73581,2229,117961,118300,118450,119192,135136,119184,119194
32743,1,31639,50976,117961,118413,119968,117905,117906,290919,117908
32744,1,42093,5396,117961,118343,119993,118321,117906,290919,118322
32745,1,5491,27394,117961,118343,119142,118685,152298,308574,118687
32746,1,27133,2610,117961,118327,121979,118321,117906,290919,118322
32747,1,27785,4871,117961,118300,125872,120006,159698,118424,120008
32748,1,80247,2299,117961,117962,119223,120516,146694,120518,120519
32749,1,75915,1728,117961,118327,118507,121527,128634,118398,121529
32750,1,77178,3225,117961,118327,118929,118784,126514,290919,118786
32751,1,16442,4659,117961,118225,120663,118321,117906,290919,118322
32752,1,32529,22355,118120,118121,117920,121067,229187,121069,121070
32753,1,23096,53282,118290,118291,120211,117985,121679,19793,117987
32754,1,52684,59712,117916,118150,117884,117885,117913,117887,117888
32755,1,42085,54618,117961,118052,118821,117905,240983,290919,117908
32756,1,79969,3221,120342,120343,124133,118728,244948,118295,118730
32757,1,16639,4945,117961,118300,118360,118129,122064,118131,118132
32758,1,33118,5423,117961,118327,118391,123045,123107,120518,123047
32759,1,15679,46503,120140,120141,121589,120952,120953,118453,120954
32760,1,17308,1550,117961,118225,123173,119093,123174,119095,119096
32761,1,16354,25618,117961,118327,118320,122060,122060,290919,122062
32762,1,6921,3954,117961,118343,120291,118422,300136,118424,118425
32763,1,32147,3883,117961,118343,119987,118784,118785,290919,118786
32764,1,23497,16971,117961,118300,119993,118321,240983,290919,118322
32765,1,25139,311198,91261,118026,122392,121143,173805,249618,121145
32766,1,34924,28805,117961,118327,120299,124922,152038,118612,124924
32767,1,80574,55643,118256,118257,117945,280788,280788,292795,119082
32768,1,14354,59575,117916,118150,117920,118568,122142,19721,118570

In [50]:
X=train_dataset.iloc[:, 1:11]

In [51]:
Y=train_dataset.iloc[:, 0]

In [52]:
Y.head()

0    1
1    1
2    1
3    1
4    1
Name: ACTION, dtype: int64

In [53]:
X

,RESOURCE,MGR_ID,ROLE_ROLLUP_1,ROLE_ROLLUP_2,ROLE_DEPTNAME,ROLE_TITLE,ROLE_FAMILY_DESC,ROLE_FAMILY,ROLE_CODE
0,39353,85475,117961,118300,123472,117905,117906,290919,117908
1,17183,1540,117961,118343,123125,118536,118536,308574,118539
2,36724,14457,118219,118220,117884,117879,267952,19721,117880
3,36135,5396,117961,118343,119993,118321,240983,290919,118322
4,42680,5905,117929,117930,119569,119323,123932,19793,119325
5,45333,14561,117951,117952,118008,118568,118568,19721,118570
6,25993,17227,117961,118343,123476,118980,301534,118295,118982
7,19666,4209,117961,117969,118910,126820,269034,118638,126822
8,31246,783,117961,118413,120584,128230,302830,4673,128231
9,78766,56683,118079,118080,117878,117879,304519,19721,117880
10,4675,3005,117961,118413,118481,118784,117906,290919,118786
11,15030,94005,117902,118041,119238,119093,138522,119095,119096
12,79954,46608,118315,118463,122636,120773,123148,118960,120774
13,4675,50997,91261,118026,118202,119962,168365,118205,119964
14,95836,18181,117961,118343,118514,118321,117906,290919,118322
15,19484,6657,118219,118220,118221,117885,117886,117887,117888
16,114267,23136,117961,118052,119742,118321,117906,290919,118322
17,35197,57715,117961,118446,118701,118702,118703,118704,118705
18,86316,7002,117961,118343,123125,118278,132715,290919,118279
19,27785,5636,117961,118413,122007,118321,117906,290919,118322
20,37427,5220,117961,118300,118458,120006,303717,118424,120008
21,15672,111936,117961,118300,118783,117905,240983,290919,117908
22,92885,744,117961,118300,119181,118777,279443,308574,118779
23,1020,85475,117961,118300,120410,118321,117906,290919,118322
24,4675,7551,117961,118052,118867,118259,117906,290919,118261
25,41334,28253,118315,118463,123089,118259,128796,290919,118261
26,77385,14829,117961,118052,119986,117905,117906,290919,117908
27,20273,11506,118216,118587,118846,179731,128361,117887,117973
28,78098,46556,118090,118091,117884,118568,165015,19721,118570
29,79328,4219,117961,118300,120312,120313,144958,118424,120315
...,...,...,...,...,...,...,...,...,...
32739,20293,27915,117926,117927,117920,118568,281735,19721,118570
32740,40867,3197,117961,118386,120361,117905,117906,290919,117908
32741,22402,6199,117961,118225,120663,118321,117906,290919,118322
32742,73581,2229,117961,118300,118450,119192,135136,119184,119194
32743,31639,50976,117961,118413,119968,117905,117906,290919,117908
32744,42093,5396,117961,118343,119993,118321,117906,290919,118322
32745,5491,27394,117961,118343,119142,118685,152298,308574,118687
32746,27133,2610,117961,118327,121979,118321,117906,290919,118322
32747,27785,4871,117961,118300,125872,120006,159698,118424,120008
32748,80247,2299,117961,117962,119223,120516,146694,120518,120519
32749,75915,1728,117961,118327,118507,121527,128634,118398,121529
32750,77178,3225,117961,118327,118929,118784,126514,290919,118786
32751,16442,4659,117961,118225,120663,118321,117906,290919,118322
32752,32529,22355,118120,118121,117920,121067,229187,121069,121070
32753,23096,53282,118290,118291,120211,117985,121679,19793,117987
32754,52684,59712,117916,118150,117884,117885,117913,117887,117888
32755,42085,54618,117961,118052,118821,117905,240983,290919,117908
32756,79969,3221,120342,120343,124133,118728,244948,118295,118730
32757,16639,4945,117961,118300,118360,118129,122064,118131,118132
32758,33118,5423,117961,118327,118391,123045,123107,120518,123047
32759,15679,46503,120140,120141,121589,120952,120953,118453,120954
32760,17308,1550,117961,118225,123173,119093,123174,119095,119096
32761,16354,25618,117961,118327,118320,122060,122060,290919,122062
32762,6921,3954,117961,118343,120291,118422,300136,118424,118425
32763,32147,3883,117961,118343,119987,118784,118785,290919,118786
32764,23497,16971,117961,118300,119993,118321,240983,290919,118322
32765,25139,311198,91261,118026,122392,121143,173805,249618,121145
32766,34924,28805,117961,118327,120299,124922,152038,118612,124924
32767,80574,55643,118256,118257,117945,280788,280788,292795,119082
32768,14354,59575,117916,118150,117920,118568,122142,19721,118570

In [54]:
# Importing the dataset]
dataset_c = pd.read_csv('data/test.csv')
test_dataset= dataset_c.copy()

In [55]:
X_test=test_dataset.iloc[:, 1:11]

In [56]:
from sklearn.svm import SVC
svc_reg=SVC()
svc_reg.fit(X, Y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [57]:
y_pred=svc_reg.predict(X_test)

In [58]:
print(y_pred)

[1 1 1 ..., 1 1 1]

In [59]:
from sklearn.ensemble import RandomForestClassifier
regressorrf = RandomForestClassifier(n_estimators = 10, random_state = 0)
regressorrf.fit(X, Y)

y_pred=regressorrf.predict(X_test)

In [60]:
import xlwt
from tempfile import TemporaryFile
book = xlwt.Workbook()
sheet1 = book.add_sheet('sheet1')




for i,e in enumerate(y_pred):
    sheet1.write(i,1,e)

name = "random1.xls"
book.save(name)
book.save(TemporaryFile())

In [61]:
X['RESOURCE'].value_counts()

4675      839
79092     484
25993     409
75078     409
3853      404
6977      299
75834     299
32270     295
42085     247
17308     239
1020      236
13878     220
42093     204
18418     192
7543      186
23921     167
278393    163
34924     161
79121     157
28149     137
18072     136
20364     135
39262     129
14354     127
23096     126
75901     115
15064     113
33054     108
20897     104
33642      99
         ...
35046       1
92378       1
100413      1
79728       1
79792       1
36894       1
28635       1
59370       1
45057       1
30629       1
18462       1
38809       1
77905       1
42879       1
75631       1
39012       1
30565       1
18275       1
79693       1
97530       1
28793       1
18243       1
20290       1
26407       1
43202       1
35014       1
75535       1
30936       1
89856       1
16376       1
Name: RESOURCE, Length: 7518, dtype: int64

In [62]:
X2=pd.get_dummies(X,drop_first=True)

In [63]:
X2

,RESOURCE,MGR_ID,ROLE_ROLLUP_1,ROLE_ROLLUP_2,ROLE_DEPTNAME,ROLE_TITLE,ROLE_FAMILY_DESC,ROLE_FAMILY,ROLE_CODE
0,39353,85475,117961,118300,123472,117905,117906,290919,117908
1,17183,1540,117961,118343,123125,118536,118536,308574,118539
2,36724,14457,118219,118220,117884,117879,267952,19721,117880
3,36135,5396,117961,118343,119993,118321,240983,290919,118322
4,42680,5905,117929,117930,119569,119323,123932,19793,119325
5,45333,14561,117951,117952,118008,118568,118568,19721,118570
6,25993,17227,117961,118343,123476,118980,301534,118295,118982
7,19666,4209,117961,117969,118910,126820,269034,118638,126822
8,31246,783,117961,118413,120584,128230,302830,4673,128231
9,78766,56683,118079,118080,117878,117879,304519,19721,117880
10,4675,3005,117961,118413,118481,118784,117906,290919,118786
11,15030,94005,117902,118041,119238,119093,138522,119095,119096
12,79954,46608,118315,118463,122636,120773,123148,118960,120774
13,4675,50997,91261,118026,118202,119962,168365,118205,119964
14,95836,18181,117961,118343,118514,118321,117906,290919,118322
15,19484,6657,118219,118220,118221,117885,117886,117887,117888
16,114267,23136,117961,118052,119742,118321,117906,290919,118322
17,35197,57715,117961,118446,118701,118702,118703,118704,118705
18,86316,7002,117961,118343,123125,118278,132715,290919,118279
19,27785,5636,117961,118413,122007,118321,117906,290919,118322
20,37427,5220,117961,118300,118458,120006,303717,118424,120008
21,15672,111936,117961,118300,118783,117905,240983,290919,117908
22,92885,744,117961,118300,119181,118777,279443,308574,118779
23,1020,85475,117961,118300,120410,118321,117906,290919,118322
24,4675,7551,117961,118052,118867,118259,117906,290919,118261
25,41334,28253,118315,118463,123089,118259,128796,290919,118261
26,77385,14829,117961,118052,119986,117905,117906,290919,117908
27,20273,11506,118216,118587,118846,179731,128361,117887,117973
28,78098,46556,118090,118091,117884,118568,165015,19721,118570
29,79328,4219,117961,118300,120312,120313,144958,118424,120315
...,...,...,...,...,...,...,...,...,...
32739,20293,27915,117926,117927,117920,118568,281735,19721,118570
32740,40867,3197,117961,118386,120361,117905,117906,290919,117908
32741,22402,6199,117961,118225,120663,118321,117906,290919,118322
32742,73581,2229,117961,118300,118450,119192,135136,119184,119194
32743,31639,50976,117961,118413,119968,117905,117906,290919,117908
32744,42093,5396,117961,118343,119993,118321,117906,290919,118322
32745,5491,27394,117961,118343,119142,118685,152298,308574,118687
32746,27133,2610,117961,118327,121979,118321,117906,290919,118322
32747,27785,4871,117961,118300,125872,120006,159698,118424,120008
32748,80247,2299,117961,117962,119223,120516,146694,120518,120519
32749,75915,1728,117961,118327,118507,121527,128634,118398,121529
32750,77178,3225,117961,118327,118929,118784,126514,290919,118786
32751,16442,4659,117961,118225,120663,118321,117906,290919,118322
32752,32529,22355,118120,118121,117920,121067,229187,121069,121070
32753,23096,53282,118290,118291,120211,117985,121679,19793,117987
32754,52684,59712,117916,118150,117884,117885,117913,117887,117888
32755,42085,54618,117961,118052,118821,117905,240983,290919,117908
32756,79969,3221,120342,120343,124133,118728,244948,118295,118730
32757,16639,4945,117961,118300,118360,118129,122064,118131,118132
32758,33118,5423,117961,118327,118391,123045,123107,120518,123047
32759,15679,46503,120140,120141,121589,120952,120953,118453,120954
32760,17308,1550,117961,118225,123173,119093,123174,119095,119096
32761,16354,25618,117961,118327,118320,122060,122060,290919,122062
32762,6921,3954,117961,118343,120291,118422,300136,118424,118425
32763,32147,3883,117961,118343,119987,118784,118785,290919,118786
32764,23497,16971,117961,118300,119993,118321,240983,290919,118322
32765,25139,311198,91261,118026,122392,121143,173805,249618,121145
32766,34924,28805,117961,118327,120299,124922,152038,118612,124924
32767,80574,55643,118256,118257,117945,280788,280788,292795,119082
32768,14354,59575,117916,118150,117920,118568,122142,19721,118570

In [64]:
df = pd.DataFrame({'name': ['Manie', 'Joyce', 'Ami'],
                   'Org':  ['ABC2', 'ABC1', 'NSV2'],
                   'Dept': ['Finance', 'HR', 'HR']        
        })


df_2 = pd.get_dummies(df,drop_first=True)

In [65]:
df_2

   Dept_HR  Org_ABC2  Org_NSV2  name_Joyce  name_Manie
0        0         1         0           0           1
1        1         0         0           1           0
2        1         0         1           0           0

In [66]:
df

      Dept   Org   name
0  Finance  ABC2  Manie
1       HR  ABC1  Joyce
2       HR  NSV2    Ami

In [67]:
X.head()

,RESOURCE,MGR_ID,ROLE_ROLLUP_1,ROLE_ROLLUP_2,ROLE_DEPTNAME,ROLE_TITLE,ROLE_FAMILY_DESC,ROLE_FAMILY,ROLE_CODE
0,39353,85475,117961,118300,123472,117905,117906,290919,117908
1,17183,1540,117961,118343,123125,118536,118536,308574,118539
2,36724,14457,118219,118220,117884,117879,267952,19721,117880
3,36135,5396,117961,118343,119993,118321,240983,290919,118322
4,42680,5905,117929,117930,119569,119323,123932,19793,119325

In [68]:
X.isnull().values.any()

False

In [69]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_0 = LabelEncoder()
X.iloc[:, 0] = labelencoder_X_0.fit_transform(X.iloc[:, 0])

In [72]:
X.head()

,RESOURCE,MGR_ID,ROLE_ROLLUP_1,ROLE_ROLLUP_2,ROLE_DEPTNAME,ROLE_TITLE,ROLE_FAMILY_DESC,ROLE_FAMILY,ROLE_CODE
0,3050,85475,117961,118300,123472,117905,117906,290919,117908
1,644,1540,117961,118343,123125,118536,118536,308574,118539
2,2706,14457,118219,118220,117884,117879,267952,19721,117880
3,2615,5396,117961,118343,119993,118321,240983,290919,118322
4,3616,5905,117929,117930,119569,119323,123932,19793,119325